### ISSUE TITLE
Will the Data Be Made Available?

### ISSUE THREAD

**Issue by hendrycks** [mbaradad/learning_with_noise#1]
Will a download to the samples themselves be made available? This would be more convenient than regenerating the data. Likewise the AlexNets trained on these datasets would be helpful too.

**Comment by mbaradad** [comment]
Thanks for the interest! Yes, we plan to do a full release but it is taking a bit more time than expected. Hopefully, we will have it in 1-2 weeks.

**Comment by yusukefukuju** [comment]
I'm really looking forward to seeing it !

**Comment by mbaradad** [comment]
Hi, we have just released the data + training code + pre-trained encoders for the small-scale experiments described in the paper. We plan to release the large-scale experiments and the image generation code in the following weeks.
