### ISSUE TITLE
Hi, would you mind opening source the generators?

### ISSUE THREAD

**Issue by wizard1203** [mbaradad/learning_with_noise#2]
Hi, thanks for your awesome works. Would you mind opening source the generators?

**Comment by mbaradad** [comment]
Thanks for your interest! We plan to release them after ICML deadline (as we are busy on that right now). If you need the generators before, we could share the code as it is, though we plan to make it more user-friendly when we do the proper release.

**Comment by wizard1203** [comment]
Thank you! Really appreciate that you will open source them. I can wait it after the ICML deadline.

**Comment by mbaradad** [comment]
We have just released the data generators + large-scale training code. Sorry for the delay and hope you find them useful!
