### ISSUE TITLE
VTAB evaluation

### ISSUE THREAD

**Issue by yangyu12** [mbaradad/learning_with_noise#3]
Hi,
    Nice work! Thanks for sharing the source code. I wonder how should we evaluate the pre-trained model on VTAB datasets? My question is should the pre-trained model be fixed and evaluated with linear classification or is it finetuned. If you can also release that part of the codes, it will be great. Thanks a lot!

**Comment by mbaradad** [comment]
Thanks for your interest and for pointing this out. We dump the VTAB datasets using the vtab code in: https://github.com/google-research/task_adaptation, and then linearly evaluate (fixing the encoder network), as explained in the paper with the script in: https://github.com/mbaradad/learning_with_noise/blob/main/scripts/train_align_uniform/linear_eval_vtab.sh. 

We forgot about releasing the code to generate the VTAB datasets it in the previous release, but we will try to release it in the following days.

**Comment by yangyu12** [comment]
Thanks for your reply! Look forward to the release of VTAB evaluation code!

**Comment by mbaradad** [comment]
Hi, we have added code to dump the VTAB datasets in:
`scripts/generate_vtab_datasets/`
See the README.md there on how to execute it.
